-- INSERT INTO notifications (user_id, type, reference_id, message, is_read) VALUES 
-- (1, 'po_created', 1, 'Purchase Order #1 has been created', false),
-- (1, 'po_status_updated', 1, 'Purchase Order #1 status changed to confirmed', FALSE);