INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('85822412', 'ordinary workers', 'Day', '1773', '276', '193');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('14942603', 'Product. Portland Cement. Type 1 Cement. Bags. Delivered to site.', 'Bag', '166', '19', '172');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('3356886', 'Equipment operator. Road roller', 'Hour', '328', '74', '122');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('99529223', 'Product: High-pressure concrete floor tiles (for Class C sidewalks, flat tiles). 60mm thick. Square.', 'm²', '825', '85', '97');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('36913810', 'Products. Metal Materials. Wire', 'kg', '39', '7', '93');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('32868828', 'Technician. formwork', 'Day', '2459', '437', '91');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('29958838', 'Products. Occupational Safety and Health. Protective Equipment. Foot. Safety Shoes', 'Pair', '603', '137', '78');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('18728463', 'Other technical workers', 'Day', '2719', '308', '76');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('98847493', 'Products. Metal Materials. Steel. Steel Plates', 'kg', '27', '5', '76');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('13756669', 'Machine operator. Compactor', 'Hour', '386', '24', '72');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('90825067', 'Products. Occupational Safety and Health. Protective Equipment. Head. Helmets', 'Piece', '199', '34', '71');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('99410741', 'Machine operator. Asphalt spreader', 'Hour', '375', '47', '67');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('73197857', 'Products. Iron', 'kg', '42', '8', '58');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('11668732', 'Products. Asphalt transparent layer. Medium-gel oil-soluble asphalt. MC-70', 'L', '33', '3', '51');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('79254563', 'Products. Selective backfill materials. Graded aggregates', '㎥', '689', '24', '51');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('56629388', 'Products. Markings. Road. Reflective. Tempered glass', 'Piece', '211', '29', '50');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('4265799', 'Product. Ready-mix concrete material cost. 210kgf/cm². Type 1 cement. Delivery to construction site.', '㎥', '2526', '170', '50');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('3999315', 'Product: High-pressure concrete floor tiles (for Class C sidewalks, flat tiles). 30mm thick. Square.', 'm²', '514', '27', '48');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('12575562', 'Machine tool operator. Mobile crane', 'Hour', '388', '32', '46');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('29345092', 'Product. Plywood. Thickness 15mm', 'm²', '272', '27', '46');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('31227216', 'Products. Granules. Fine Granules', 'L.㎥', '734', '79', '46');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('67827638', '(Used as a crusher)', 'Hour', '1427', '296', '45');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('80801586', 'Product. Ready-mix concrete material cost. 140kgf/cm². Type 1 cement. Delivery to construction site.', '㎥', '2310', '139', '45');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('3561597', 'Products. Asphalt adhesive layer. Emulsified asphalt', 'kg', '20', '1', '44');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('75329037', 'Products. Iron nails. Galvanized', 'kg', '35', '3', '44');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('26687537', 'Technician. Measurement', 'Day', '2248', '366', '43');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('96102525', 'Machine operator. Planer', 'Hour', '332', '55', '42');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('87226012', 'Machine tool operator. Pump', 'Hour', '380', '45', '41');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('94130244', 'Machine operator. Cleaning machine', 'Hour', '382', '46', '41');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('73140807', 'Machine operator. Asphalt pavement paving machine', 'Hour', '354', '63', '39');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('56306997', 'Products. Occupational Safety and Health. Protective Equipment. Hands. Work Gloves', 'Pair', '44', '8', '39');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('29587039', 'Rebar technician. Rebar cutting', 'Hour', '403', '21', '35');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('60291817', 'Products. Marking. Heat-treated polyester', 'kg', '60', '17', '34');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('79089901', 'Products. Planting. Fertilizer. Organic Fertilizer', 'kg', '17', '4', '33');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('37338124', 'Products. Occupational Safety and Health. General Equipment. Fire Extinguishers', 'Piece', '1181', '179', '33');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('872248', 'Products. Occupational Safety and Health. Protective Equipment. Body. Reflective Vests', 'Piece', '200', '37', '33');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('21429110', 'Products. Permeable Paving. Porous Asphalt Concrete', 'Metric Ton', '2717', '0', '33');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('93702683', 'Product: Reinforced concrete pipe (Type B). D=500mm. Tertiary pipe', 'Piece', '3694', '136', '33');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('56722344', 'Products: Waterstop', 'm', '195', '60', '32');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('45667651', 'Products. Toner', 'kg', '80', '18', '32');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('37295260', 'Product. Ready-mix concrete material cost. 175kgf/cm². Type 1 cement. Delivery to construction site.', '㎥', '2437', '91', '32');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('20868105', 'Product. Marking. Pavement. Reflective. Metal', 'Piece', '231', '6', '31');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('28898923', 'Products. Marking. Glass Beads', 'kg', '73', '9', '30');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('45176955', 'Products. Granules. Coarse Granules', 'L.㎥', '542', '16', '30');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('13718431', 'Product: High-pressure concrete floor tiles. Thickness: 60mm', 'm²', '772', '103', '30');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('12448136', '35-ton gross weight trailer. 40-foot lowboard', 'Trip', '4523', '276', '30');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('50992979', 'Products. Divider rod', 'Piece', '1079', '107', '29');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('12981052', 'Product: Reinforced concrete pipe (Type B). D=400mm. Tertiary pipe', 'Piece', '2435', '306', '29');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('48181396', 'Product. Flexible surfacing. Asphalt putty. Viscosity AC-20', 'kg', '17', '0', '28');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('46164955', 'Product: Reinforced concrete pipe (Type B). D=1200mm. Tertiary pipe', 'Piece', '16633', '315', '28');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('81030736', 'Products. Timber for formwork. Boards', '㎥', '2892', '359', '27');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('35503389', 'Products. Occupational Safety and Health. General Equipment. Safety Signs', 'Piece', '1932', '218', '27');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('5831819', 'Product. Slope stabilization horizontal drainage pipe. Drain pipe. PVC pipe (no holes). Pipe diameter = 50mm', 'm', '53', '9', '27');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('97942942', 'Products. Metal joining. (Mechanical joining, structural). Nuts', 'Piece', '119', '3', '27');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('61662963', 'Product: Reinforced concrete pipe (Type B). D = 600mm. Grade 3 pipe. Includes pipe fittings.', 'm', '2182', '287', '27');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('71971316', '1.5M3. Wheeled', 'Hour', '1222', '27', '26');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('16753883', 'Products. Occupational Safety and Health. General Equipment. Hygiene Signs', 'Piece', '2250', '0', '26');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('50806024', 'Product: Reinforced concrete pipe (Type B). D = 300mm. Grade 3 pipe. Includes pipe fittings.', 'm', '1096', '140', '26');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('10576383', 'Machine tool operator. Motor grader', 'Hour', '400', '2', '25');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('74093639', 'Products. Structural steel. General structural rolled steel. A36', 'kg', '34', '1', '25');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('39349722', 'Product: Reinforced concrete pipe (Type B). D = 900mm. Grade 3 pipe. Includes pipe fittings.', 'm', '3948', '162', '25');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('84374605', 'Machine tool operator. Bulldozer', 'Hour', '399', '7', '24');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('83016315', 'Machine Operator Technician. Air Compressor', 'Hour', '392', '40', '24');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('48537831', 'Machine tool operator. Rock drill', 'Hour', '392', '40', '24');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('77490893', 'Products. Grass Planting. Organic Fertilizer', 'kg', '18', '6', '24');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('25808537', 'Product. Marking. Reflective. Tempered glass. Height <1.9cm', 'Piece', '334', '1', '24');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('94566031', 'Product: Reinforced concrete pipe (Type B). D = 1200mm. Tertiary pipe. Includes pipe fittings.', 'm', '7081', '118', '24');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('9335534', 'Product: Reinforced concrete pipe (Type B). D=500mm. Grade III pipe. Installation fee', 'm', '1678', '190', '24');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('6150444', 'Products. Occupational Safety and Health. Protective Equipment. Working at Heights. Safety Belts', 'Piece', '1232', '145', '23');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('88753260', 'Product: Reinforced concrete pipe (Type B). D = 1500mm. Tertiary pipe. Includes pipe fittings.', 'm', '10716', '172', '23');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('30587988', 'Products: Steel Formwork', 'm²', '743', '56', '23');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('38840994', 'Products. Occupational safety and health. Protective equipment. Hands. Sleeves. Welding fire protection', 'Pair', '136', '3', '22');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('10709497', 'Products. Washed Stone. Yilan Stone', 'kg', '20', '1', '21');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('31244663', 'Product. Rock bolt. Self-drilling rock bolt. Anchor diameter = 25mm. L = 6m', 'm', '1471', '38', '19');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('13556182', 'Products. Marking Lines. Glass Beads. Category 1', 'kg', '44', '15', '19');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('51019678', 'Products. Graded aggregate base. Graded crushed stone', 'L.㎥', '704', '79', '19');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('37308985', 'Products. Small stones', 'kg', '20', '3', '17');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('60855700', 'Products. Construction Signs', 'Piece', '1543', '40', '17');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('85320121', 'Product: Reinforced concrete pipe (Type B). D = 450mm. Grade 3 pipe. Includes pipe fittings.', 'm', '1376', '4', '17');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('48966946', 'Product: High-pressure concrete floor tiles. Thickness: 30mm', 'm²', '580', '58', '17');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('21831063', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. Steel bar chemical composition analysis.', 'root', '1338', '259', '16');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('49684848', 'Plasterer-Painter', 'Day', '2244', '494', '16');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('47683626', 'Product. Ready-mix concrete material cost. 280kgf/cm². Type 1 cement. Delivery to construction site.', '㎥', '2863', '238', '16');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('28119557', 'Machine tool operator', 'Day', '2305', '248', '15');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('89949389', 'Product. Ready-mixed concrete material cost. 280kgf/cm2. Type 1 cement', '㎥', '2969', '183', '15');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('35833156', 'Product. Ready-mix concrete material cost. 350kgf/cm². Type 1 cement. Delivery to construction site.', '㎥', '2810', '422', '15');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('94196727', '35-ton gross weight trailer. 20-foot lowboard', 'Trip', '5443', '1079', '15');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('91744214', 'Products. Plain formwork', 'm²', '326', '33', '14');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('86977837', 'Products. Selective backfill materials. Permeable materials. Sand', 'L.㎥', '678', '56', '14');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('9583482', 'Horticultural technician', 'Day', '2289', '262', '13');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('81756179', 'Products. Occupational Safety and Health. Protective Equipment. Eye Protection. Goggles. Dust Protection Goggles', 'Piece', '239', '31', '13');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('85225343', 'Products. Metal Materials. Wire Mesh. Galvanized', 'kg', '39', '7', '13');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('22969840', 'Product. (Non-removable formwork, wood)', 'm²', '191', '23', '12');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('71691040', 'Products. Ecological slope protection. Straw mat covering', 'm²', '17', '2', '12');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('97861742', 'Products. Occupational safety and health. Protective equipment. Body. Raincoats and pants', 'Set', '308', '19', '12');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('32857966', 'Products. Selective backfill materials. Permeable materials. Gravel', 'L.㎥', '654', '55', '12');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('21931511', 'Formwork technician', 'Day', '2254', '436', '11');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('62043515', 'Product. Construction notice board. Aluminum. 120cm long x 75cm wide', 'Piece', '2901', '531', '11');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('50929647', 'Products. Timber for formwork', 'm²', '388', '83', '11');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('36231783', 'Products: Galvanized grating and frame', 'kg', '53', '6', '11');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('85899313', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. Heat-treated steel bar quality assessment tests.', 'root', '1582', '57', '10');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('92363534', 'Products. Planting. Fertilizer. Fast-acting chemical fertilizer', 'kg', '18', '5', '10');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('74752529', 'Product. Aggregate. Fine aggregate. (Coarse sand, for mixing)', '㎥', '783', '89', '10');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('29476249', 'Products. Occupational safety and health. Protective equipment. Water rescue equipment. Lifebuoys', 'Piece', '740', '174', '10');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('91887369', 'Products.', 'kg', '31', '8', '10');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('43524491', 'Manual demolition. Road excavation. Asphalt concrete. Shipping included.', '㎥', '2400', '0', '9');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('7507864', 'Backfill of structures. Backfill of raw materials', '㎥', '177', '10', '9');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('30742311', 'Product. (No need to dismantle the formwork, steel)', 'm²', '453', '34', '9');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('4308421', 'Product. Standard formwork', 'm²', '323', '76', '9');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('42339391', 'Product. Waterstop. PVC. Type A. 220x9mm', 'm', '266', '27', '9');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('53843426', 'Products. Occupational Safety and Health. Protective Equipment. Working at Heights. Fall Arresters', 'Piece', '5574', '825', '9');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('35935572', 'Products. Metal Materials. Steel. H-Beam', 'kg', '30', '4', '9');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('8883684', 'Products. Metal Materials. Iron Wire. Galvanized', 'kg', '41', '11', '9');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('28317637', 'Steel Rebar Technician', 'Day', '2692', '361', '9');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('76125617', 'Product. Road marking. Heat-treated polyester. Reflective. 2mm thick', 'm²', '168', '14', '8');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('96356822', 'Product. Asphalt adhesive. Fast-setting oil-soluble asphalt. RC-70', 'L', '31', '10', '8');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('42235350', 'Product. Granules. Fine granules. (Fine sand, for finishing)', '㎥', '926', '126', '8');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('28538251', 'Products: Galvanized grating cover', 'kg', '70', '9', '8');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('87971488', 'Product. Precast concrete. S1 precast trench cover. 100cm wide x 50cm long', 'Piece', '1034', '212', '8');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('67005685', 'Decorative carpentry, furniture carpentry, door and window carpentry technicians.', 'Hour', '375', '0', '8');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('53100814', 'Laying technician', 'Day', '2337', '320', '8');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('86282117', 'Electric welding technician', 'Day', '3321', '250', '8');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('61586053', 'Cement mortar. 1:3. Continuous work and material', '㎥', '3029', '659', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('19175900', 'Product. Portland Cement. Bulk', 'kg', '4', '1', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('35551614', 'Product. Seam filler. Styrofoam. 1.0 < Thickness ≤ 3.0 cm', 'm²', '63', '4', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('18740864', 'Products. Construction Fence. Overflow Block', 'm', '164', '35', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('33101783', 'Products. Flexible Paving. Coarse Aggregate', '㎥', '877', '116', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('99990728', 'Products. Grass Planting. Grass Seed Spraying. Mixed Grass Seed', 'kg', '583', '20', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('75345555', 'Products. Occupational Safety and Health. Protective Equipment. Respiratory. Air Respirators', 'Set', '5000', '0', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('72340307', 'Products. Occupational Safety and Health. Protective Equipment. Foot. Rainboots', 'Pair', '279', '73', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('35264581', 'Products. Occupational Safety and Health. Protective Equipment. Body. Welding Jackets', 'Set', '671', '45', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('78461803', 'Products. Occupational safety and health. Protective equipment. Head. Hard hat. Construction site use', 'Piece', '226', '35', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('57503414', 'Product. Temporary retaining pile facilities. Steel sheet pile. L=9m', 'piece', '1083', '7', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('78320463', 'Product: Reinforced concrete pipe (Type B). D=1000mm. Secondary pipe', 'm', '3269', '155', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('53606628', 'Product: Reinforced concrete pipe (Type B). D=1200mm. Secondary pipe', 'm', '5230', '249', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('48586340', 'Product: Reinforced concrete pipe (Type B). D=1500mm. Tertiary pipe', 'Piece', '21382', '3666', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('29436733', 'Product: Reinforced concrete pipe (Type B). D=1500mm. Secondary pipe', 'm', '7628', '363', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('18566572', 'Product: Reinforced concrete pipe (Type B). D=300mm. Secondary pipe', 'm', '981', '47', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('68387461', 'Product. Sump. Stainless steel steps. D=19mm', 'Piece', '500', '0', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('66238574', 'Steel pipe construction scaffolding technician', 'Day', '2257', '287', '7');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('12201654', '1.2M3. Wheeled', 'Hour', '1115', '15', '6');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('6323852', 'Technician. Daytime. Measure', 'Day', '2417', '186', '6');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('14716857', 'Construction measurement. Wire measurement', 'km', '7500', '1', '6');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('20514014', 'Products: Geotextiles, Engineering Nonwovens', 'm²', '69', '5', '6');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('84214382', 'Products. Clamps. Three-ply (water-resistant)', 'm²', '71', '17', '6');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('21472420', 'Products. Non-shrinkage concrete. Non-shrinkage chemical admixtures', 'kg', '176', '3', '6');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('91332642', 'Products. Occupational safety and health. Protective equipment. Accidental injury rescue equipment. First aid kits', 'Piece', '738', '213', '6');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('56661351', 'Product. Temporary retaining pile facilities. Steel sheet pile. L=13m', 'piece', '1170', '0', '6');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('80048665', 'Product. Snake Cage. Oval 60cm*100cm', 'm', '397', '0', '6');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('8526544', 'Products. Selective backfill materials. Permeable materials. Pebbles', '㎥', '1065', '280', '6');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('51642594', 'Products. Metal Materials. Galvanized Steel Pipes', 'kg', '55', '0', '6');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('51220073', 'Products. Rebar. SD280. Site delivery', 'Metric Ton', '21250', '559', '6');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('79978790', 'Product: Reinforced concrete pipe (Type B). D=700mm. Tertiary pipe', 'Piece', '6562', '439', '6');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('62820592', 'Prestressed anchor. Fees for moving holes, erecting and dismantling scaffolding', 'm', '200', '0', '6');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('71016525', 'Manual demolition. Structural demolition (demolition of structures other than buildings). Concrete', '㎥', '2872', '184', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('33744231', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. Steel reinforcement appearance testing.', 'root', '324', '54', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('74252722', 'Underground distribution pipelines. Backfill. Crushed stone 10-50mm', '㎥', '617', '63', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('1540956', 'Underground distribution pipelines. Backfill. Graded materials', '㎥', '593', '39', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('91306093', 'Technician. Day. formwork', 'Day', '3260', '301', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('96733645', 'Technician. Steel', 'Hour', '355', '43', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('15374874', 'Construction auxiliary facilities, scaffolding, steel pipes, installation and disassembly (including rental)', 'm²', '369', '40', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('91497616', 'Abandoned land area fees (including soil and water conservation)', 'B.㎥', '184', '20', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('72070937', 'Equipment operator. Equipment lifting technician.', 'Day', '3095', '210', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('35812670', 'Products. Traffic Cone', 'Piece', '210', '20', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('86028436', 'Products. Traffic Cone. Connecting Rod', 'Piece', '77', '16', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('45657579', 'Products: Sidewalk Surfaces, Paving Bricks (High Pressure)', 'm²', '990', '254', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('14972279', 'product. plywood. Thick 18mm', 'm²', '288', '27', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('39392920', 'Products. Grass. Carpetgrass', 'm²', '207', '56', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('58353204', 'Products. Movable chevaux de frise', 'Piece', '904', '120', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('21227574', 'Product. Non-shrinkage cement mortar. Compressive strength 350 kgf/cm2', '㎥', '14190', '1601', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('60897765', 'Products. Occupational Safety and Health. Protective Equipment. Inductance Prevention. Insulation Protection Sleeves', 'm', '70', '0', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('435578', 'Products. Temporary Facilities. Lighting Equipment', 'piece', '1138', '170', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('96917555', 'Product. Metal. Iron wire. Galvanized. (#20, D=0.889mm)', 'kg', '29', '6', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('96593904', 'Products. Aluminum Sheet', 'm²', '1947', '78', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('35351479', 'Product. Ready-mixed concrete material cost. 210kgf/cm2. Type 2 cement', '㎥', '2911', '209', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('67187530', 'Product. Ready-mixed concrete material cost. 245kgf/cm2. Type 1 cement', '㎥', '2983', '14', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('23978249', 'Product. Ready-mix concrete material cost. 245kgf/cm². Type 1 cement. Delivery to construction site.', '㎥', '2540', '80', '5');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('68139880', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. A3009 Coarse aggregate (less than 37.5 mm) abrasion test method.', 'One test', '3108', '186', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('14282218', 'Quality Management. Test Specifications and Standards. Civil Engineering and Construction Inspection. A3031 Test Method for Solidity of Aggregates Using Sodium Sulfate or Magnesium Sulfate', 'One test', '9404', '0', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('83926371', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. A3288 Asphalt pavement compaction test method', 'One test', '763', '253', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('40056581', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. Gravel grading site density testing.', 'One test', '1925', '266', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('85758349', 'Spraying concrete technician', 'Day', '2600', '0', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('68137358', 'Underground distribution pipelines. Backfill. Sand', '㎥', '604', '47', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('81734598', 'engineer', 'Day', '3500', '0', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('26697396', 'Excavation of structures. Complex ground. Depth <5m. (Mechanical excavation, including pumping). Freight not included.', '㎥', '50', '0', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('20513739', 'Formwork technician. Daytime', 'Day', '3000', '0', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('50185867', 'Architectural concrete. Type C', 'm²', '443', '54', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('21682744', 'Products. Plywood', 'm²', '408', '57', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('72394227', 'Products. Fixed foam fire extinguishing equipment. Foam discharge port. Foam nozzle', 'Piece', '142', '40', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('71182864', 'Product. Flexible paving. Asphalt mortar. Viscosity AC-10. Delivery from the mixing plant.', 'kg', '17', '0', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('76758', 'Products. Grass Planting. Mixed Grass Seeds', 'kg', '398', '130', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('80388981', 'Products. Grass Planting. Seeds', 'kg', '553', '56', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('43507489', 'Products. Mobile Engineering Notice Board', 'Piece', '1080', '80', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('65579548', 'Products. Graded aggregate base. Graded crushed stone', 'L.㎥', '795', '55', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('2614124', 'Product. Temporary Conducting Equipment. Red Electric Conductor Baton', 'Piece', '330', '0', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('15014631', 'Products. Selective backfill materials. Graded aggregate. Graded crushed stone', 'L.㎥', '680', '96', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('48718453', 'Product. Ready-mix concrete material cost. 280kgf/cm². Type 2 cement. Delivery to construction site.', '㎥', '3055', '382', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('41273847', 'Product. Ready-mix concrete material cost. 350kgf/cm2. Type 2 cement', '㎥', '3883', '239', '4');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('32138745', 'Quality Management. Test Specifications and Standards. Civil Engineering and Construction Inspection. A3005 Coarse and Fine Particle Screening Method', 'One test', '3033', '450', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('7774584', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. A3252 Test method for the relationship between soil moisture content and density.', 'One test', '4667', '471', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('32329237', 'Quality Management. Test Specifications and Standards. Civil Engineering and Construction Inspection. A3293 Test Method for Plastic Flow Resistance of Asphalt Mixtures Using a Marshall Apparatus', 'One test', '3200', '566', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('76149359', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. Soil compaction tests.', 'one test', '4833', '624', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('10570592', 'Underground distribution pipes. Backfill. Asphalt (40kg package)', 'Bag', '233', '24', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('11496211', 'Underground distribution pipelines. Ready-mixed concrete. 140 kgf/cm2', '㎥', '1857', '363', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('98234974', 'Crawler type. 60~69KW. (Used as a crusher)', 'Day', '13000', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('65228535', 'Crawler type. 90~99KW. (Used as a crusher)', 'Day', '15000', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('9289546', 'Technician. Daytime. Rebar', 'Day', '2800', '163', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('71498611', 'Technician. Concrete', 'Day', '2115', '314', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('16879290', 'Construction auxiliary facilities. External construction frame dust screen. Nylon', 'm²', '29', '1', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('17232410', 'Excavation of structures. Manual excavation', '㎥', '650', '21', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('88550256', 'Machine operator. Cutting machine', 'Day', '2700', '141', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('63791320', 'Product. Stainless steel plate. Type 304', 'kg', '136', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('73793389', 'Products. Chemical additives. Early strength agents', 'kg', '30', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('22162965', 'Products. Geotextiles. Engineering nonwovens (nonwoven fabrics). CNS Class 2', 'm²', '120', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('35575298', 'Products. Geotextiles. Engineering nonwovens (nonwoven fabrics). CNS Class 4', 'm²', '87', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('70823176', 'Products. Temporary construction facilities on construction sites. Temporary toilets.', 'Piece', '17667', '2055', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('81415657', 'Products. Stone. Block. Hard Stone', 'L.㎥', '596', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('56792612', 'Products. Grass Planting. False Grass', 'm²', '82', '1', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('28427073', 'Products. Grass Planting. Taipei Grass (Manila Chi)', 'm²', '95', '4', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('72383095', 'Product. Waterstop. PVC. Type A. 150x9mm', 'm', '180', '10', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('97969689', 'Products: Seaweed Powder', 'kg', '283', '2', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('92592466', 'Products. Stone tile paving. Granite', 'm²', '2518', '26', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('26998038', 'Products. Occupational Safety and Health. General Equipment. Flashlights', 'Piece', '500', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('95690391', 'Products. Occupational Safety and Health. General Equipment. Electricity Meters (Triple Meters)', 'Piece', '1000', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('41837852', 'Products. Occupational Safety and Health. Protective Equipment. Respiratory. Masks', 'Piece', '52', '6', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('53551839', 'Products. Occupational Safety and Health. Protective Equipment. Ear. Earplugs', 'Pair', '55', '7', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('90152297', 'Products. Occupational Safety and Health. Protective Equipment. Working at Heights. Safety Nets', 'm²', '210', '57', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('87225156', 'Product. Floor tiles. Guide bricks. 300x300mm. t=60mm', 'm²', '775', '35', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('50119651', 'Products. Selective backfill material. Graded aggregate. Natural graded', 'C.㎥', '469', '62', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('58800797', 'Products. Metal joining. (Mechanical joining, structural). Shear screws', 'Piece', '100', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('69467853', 'Products. Metal Materials. Steel. Angle Steel', 'kg', '25', '4', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('60597444', 'Product. Metal. Steel. Steel plate. Thickness 2mm', 'kg', '70', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('16240908', 'Products. Steel Rebar. SD280', 'Metric Ton', '20667', '1650', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('33273328', 'Products. Steel Rebar. SD420W', 'kg', '22', '2', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('30158366', 'Products. Excavation of temporary cover plate and its support. Installation of anti-skid steel plate. Daytime construction.', 'm²', '112', '7', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('8593410', 'Product. Ready-mix concrete material cost. 210kgf/cm². Type 2 cement. Delivery to construction site.', '㎥', '2711', '194', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('45377076', 'Product: Precast concrete. L1 precast trench cover. Width 100cm x Length 90cm. Height 25cm', 'Piece', '2063', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('2823170', 'Product: Precast concrete. L2 precast trench cover. 80cm wide x 90cm long. 25cm high', 'Piece', '4320', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('78961459', 'Product. Precast concrete. S1 precast trench cover. 100cm wide x 100cm long', 'Piece', '1322', '237', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('74346088', 'Product. Precast concrete. S1 precast trench cover. 90cm wide x 50cm long', 'Piece', '667', '118', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('30885476', 'Installation technician. Drainage pipes', 'Day', '2090', '351', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('78979095', 'Road construction and restoration. Asphalt concrete pavement. 5cm', 'm²', '517', '24', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('29557077', 'Selective backfill material. Soil. Fertile soil', '㎥', '600', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('965138', 'Selective backfill material. Graded aggregate. Graded crushed stone. Used for backfilling structures.', 'C.㎥', '1235', '0', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('9528530', 'rebar. (Excluding steel bar supply, including wages, miscellaneous materials and machinery)', 'Metric Ton', '4886', '87', '3');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('95004803', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. A2006 rebar for reinforced concrete', 'root', '948', '298', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('84705205', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. Soil relative density testing.', 'One test', '6000', '1000', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('7901903', 'Quality management. Test specifications and standards. Ferrous metal smelting inspection. G2013 Metal Materials Tensile Test Method', 'one test', '1600', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('30728046', 'Earthwork. Earthwork transportation. 0≦Transport distance<5km', '㎥', '68', '3', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('9046318', 'Indoor wiring and distribution line installation technician', 'Day', '3046', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('4216175', 'Crawler type. 0.70~0.79m3. (used as a crusher)', 'Hour', '1263', '13', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('44349361', 'Ordinary formwork. For general engineering use', 'm²', '484', '34', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('9510312', 'Structural excavation. Soft rock. Mechanical excavation', '㎥', '188', '8', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('69008866', 'Cement mortar. 1:2. Continuous work and material', '㎥', '3000', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('31944441', 'Plasterer-Bricklayer', 'Day', '2300', '200', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('37376585', 'Mud water-surface material paving technician', 'Day', '2549', '251', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('89788677', 'Architectural concrete', 'm²', '1094', '207', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('65151231', 'Plain formwork. Type A', 'm²', '800', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('28754377', 'Asphalt concrete surface layer removal. Shipping cost of the removed material', '㎥', '400', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('72374753', 'Product. Stainless steel reflector. D=100cm', 'Piece', '3359', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('17758595', 'Product: Stainless steel pipe. Diameter = 5cm. Thickness 2.5mm', 'm', '450', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('97086737', 'Product. Dry powder fire extinguisher. Model 10. ABC', 'Piece', '854', '96', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('76644106', 'Product: Recycled asphalt concrete paving (dense graded, 30% recycled material)', '㎥', '2819', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('77337818', 'Products. Fixed foam fire extinguishing equipment. Sensor sprinkler head', 'Piece', '182', '1', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('63440831', 'Products. Ceiling. Exposed Shelves', 'm²', '330', '16', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('32614537', 'Product. Construction sign. Aluminum. 300cm long x 170cm wide', 'Piece', '8950', '1050', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('63481353', 'Product. Construction sign. Aluminum. 500cm long x 320cm wide', 'Piece', '35000', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('54634663', 'Products. Stone. Pebbles', '㎥', '770', '130', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('25556386', 'Product. Controlled low-strength backfill material. Aggregate for concrete. 80 kg/cm2', '㎥', '1310', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('12660194', 'Product. Construction safety net. Mesh size 2x2cm. Polypropylene.', 'm²', '27', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('13009833', 'Product. Construction Signs. Diamond Shape. Standard Side Length 70cm. Rental', 'Piece', '2050', '50', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('88447167', 'Product. Construction warning light. Small red light bulb and wire set', 'm', '41', '1', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('57854710', 'Products. Construction Warning Lights. Depreciation', 'Piece', '1550', '50', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('47553014', 'Products. Flexible Paving. Mineral Filler', 'kg', '56', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('56851760', 'Product. Planting. Added soil. Sandy loam', 'B.㎥', '388', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('55177213', 'Products. Grass Planting. Bermuda Grass (Bermudagrass)', 'm²', '73', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('62682989', 'Product. Bridge deck expansion joint. Tooth profile. 5 ≤ expansion < 10 mm', 'm', '23260', '3260', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('97854904', 'Product. Waterstop. PVC. Type A. 150x4mm', 'm', '81', '3', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('7270733', 'Products: Water flow buzzer alarm', 'Piece', '524', '66', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('90377459', 'Products. Asphalt adhesive. Emulsified asphalt. CRS-1', 'L', '19', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('87705310', 'Product. Non-shrinkage concrete. Compressive strength 350 kgf/cm2', '㎥', '25000', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('86728778', 'Product. Lighting control switch. Single cut. 15A', 'Piece', '104', '26', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('13209423', 'Products. Monitoring equipment. Subsidence observation nails. Installation including monitoring', 'Piece', '210', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('8135295', 'Products. New Jersey Guardrail. Flooded Movable Guardrail', 'Piece', '750', '250', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('54038913', 'Products. Occupational Safety and Health. Protective Equipment. Eyewear. Safety Glasses', 'Pair', '592', '18', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('97739173', 'Products. Occupational Safety and Health. Protective Equipment. Face. Welding Mask', 'Piece', '500', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('45540424', 'Products. Occupational Safety and Health. Protective Equipment. Working at Heights. Safety Ropes', 'm', '100', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('14665841', 'Products. Permeable paving. Block and hollow. Grass bricks. 5 ≤ Surface thickness < 10 cm', 'm²', '940', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('33374088', 'Products. Selective backfill material. Soil. Fertile soil', '㎥', '300', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('25714784', 'Products. Selective backfill materials. Permeable materials. Gravel', '㎥', '1050', '251', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('25529407', 'Product: Slope-stabilized horizontal drainage pipe. High-density polyethylene (HDPE) pipe (non-porous). Pipe diameter = 30mm', 'm', '1405', '143', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('71979055', 'Product. Slope stabilization horizontal drainage pipe. High-density polyethylene (HDPE) pipe (non-porous). Pipe diameter = 50mm', 'm', '2930', '298', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('60211891', 'Product. Slope stabilization horizontal drainage pipe. High-density polyethylene (HDPE) pipe (non-porous). Pipe diameter = 60mm', 'm', '4776', '486', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('18814949', 'Product. Slope stabilization horizontal drainage pipe. High-density polyethylene (HDPE) pipe (non-porous). Pipe diameter = 70mm', 'm', '5699', '580', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('56623995', 'Product. Metal joining. (Mechanical joining, structural). Bolt. General type, #8 (25mm)', 'Piece', '355', '115', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('24627347', 'Products. Metal Materials. Steel. Steel Sections', 'kg', '25', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('37385696', 'Products. Wall tiles. (Porcelain tiles, first-class quality)', 'm²', '720', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('62092888', 'Products. Wall tiles. (Porcelain mosaic tiles, first-class quality)', 'm²', '750', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('33528453', 'Products. rebar. SD280W', 'Metric Ton', '19800', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('10117988', 'Products. Steel Rebar. SD420', 'Metric Ton', '20500', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('59476001', 'Products. Rebar. Rebar Connector. D25mm', 'Piece', '120', '10', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('73863413', 'Products. Rebar. Rebar Connector. D32mm', 'Piece', '180', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('13141087', 'Products. Rebar. Rebar Connector. D36mm', 'Piece', '200', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('6789850', 'Product: Reinforced concrete pipe (Type B). D=1000mm. Tertiary pipe', 'Piece', '12730', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('87529405', 'Product: Reinforced concrete pipe (Type B). D=1350mm. Tertiary pipe', 'Piece', '22900', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('72556484', 'Product: Reinforced concrete pipe (Type B). D=300mm. Tertiary pipe', 'Piece', '3000', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('1980765', 'Product: Reinforced concrete pipe (Type B). D = 300mm. Grade 3 pipe. Excavation and backfill not included.', 'm', '1207', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('12517517', 'Product: Reinforced concrete pipe (Type B). D=400mm. Secondary pipe', 'Piece', '2412', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('31726318', 'Product: Reinforced concrete pipe (Type B). D=450mm. Tertiary pipe', 'Piece', '4100', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('22321899', 'Product: Reinforced concrete pipe (Type B). D=500mm. Secondary pipe', 'Piece', '3740', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('54547971', 'Product: Reinforced concrete pipe (Type B). D=600mm. Tertiary pipe', 'Piece', '6248', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('65181648', 'Product: Reinforced concrete pipe (Type B). D = 600mm. Grade 3 pipe. Excavation and backfill not included.', 'm', '2245', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('64606833', 'Product: Reinforced concrete pipe (Type B). D=600mm. Secondary pipe', 'Piece', '5610', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('28688676', 'Product: Reinforced concrete pipe (Type B). D=800mm. Tertiary pipe', 'Piece', '8690', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('53826716', 'Product: Reinforced concrete pipe (Type B). D = 800mm. Grade 3 pipe. Excavation and backfill not included.', 'm', '3120', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('7869910', 'Product: Reinforced concrete pipe (Type B). D=800mm. Secondary pipe', 'Piece', '8010', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('22097220', 'Product. Reinforced concrete pipe culvert. D=600mm. Three-stage pipe', 'm', '2750', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('50864911', 'Product. Reinforced concrete edge. Precast. 20 ≤ Base width < 25cm. 35 ≤ Overall height < 40cm', 'm', '650', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('289289', 'Products. Drilling piles. Stabilizing fluid additives', '㎥', '600', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('52401521', 'Products. Access Control Equipment. Access Control Machine. Card Reader', 'piece', '10100', '100', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('35594951', 'Products: Prestressed tendons', 'Metric Ton', '51200', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('61070189', 'Product. Ready-mixed concrete material cost. 140kgf/cm2. Type 1 cement', '㎥', '2500', '50', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('38285503', 'Product. Ready-mix concrete material cost. 175kgf/cm². Type 2 cement. Delivery to construction site.', '㎥', '2300', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('56775103', 'Product. Ready-mixed concrete material cost. 210kgf/cm2. Type 1 cement', '㎥', '2600', '50', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('93494928', 'Product. Ready-mix concrete material cost. 350kgf/cm2. Type 1 cement', '㎥', '3540', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('98046763', 'Product. Ready-mix concrete material cost. 420kgf/cm2. Type 2 cement', '㎥', '4330', '130', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('74593961', 'Product: Precast concrete. L1 precast trench cover. Width 100cm x Length 90cm. Height 30cm', 'Piece', '1790', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('88834863', 'Product: Precast concrete. L2 precast trench cover. 100cm wide x 90cm long. 30cm high. Contains galvanized grating.', 'Piece', '4330', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('96423126', 'Product. Precast concrete. S1 precast trench cover. 70cm wide x 100cm long', 'Piece', '1075', '25', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('65319931', 'Product. Precast concrete. S1 precast trench cover. 80cm wide x 100cm long', 'Piece', '1198', '3', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('20776478', 'Structural concrete. 140kgf/cm2', '㎥', '2000', '400', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('25487660', 'Structural concrete. Manual mixing. 210kgf/cm2', '㎥', '2868', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('39823450', 'Structural concrete. Ready-mixed. 210kgf/cm2', '㎥', '2868', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('29219319', 'Structural concrete. Ready-mixed. 210 kgf/cm². Type 1 cement.', '㎥', '2069', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('7849494', 'Structural concrete. Ready-mixed. 210 kgf/cm². Type 2 cement', '㎥', '2868', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('77736262', 'Temporary retaining pile facilities. Steel sheet pile. L=13m. Driving and pulling', 'piece', '1384', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('98748972', 'Temporary retaining pile facilities. Steel sheet pile. L=16m. Driving and pulling', 'piece', '2344', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('72772208', 'Temporary retaining pile facilities. Steel sheet pile. L=6m. Driving and pulling out', 'piece', '640', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('8181586', 'Temporary retaining pile facilities. Steel sheet pile. L=9m. Driving and pulling out', 'piece', '928', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('42091325', 'Steel drilling technician', 'Day', '2450', '50', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('7672593', 'Residual waste transport and treatment (including soil and water conservation)', '㎥', '310', '0', '2');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('6729990', '2~2.9t. Wheeled', 'Day', '7000', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('78406989', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. A3007 Test method for specific gravity and water absorption of coarse aggregates.', 'One test', '1200', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('63993471', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. A3040 Concrete slump test method.', 'One test', '500', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('67491435', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. A3045 Test method for compressive strength of concrete cylindrical specimens', 'Piece', '350', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('71286543', 'Quality management. Test specifications and standards. Civil engineering and construction inspection. A3051 Test method for compressive and flexural strength of drilled and sawn concrete specimens', 'Piece', '430', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('21130263', 'Quality Management. Test Specifications and Standards. Civil Engineering and Construction Inspection. A3147 Test Method for Thickness or Height of Compacted Specimens of Asphalt Paving Mixtures', 'One test', '400', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('7634247', 'Quality Management. Test Specifications and Standards. Civil Engineering and Construction Inspection. A3343 Test Method for Water-Soluble Chloride Ion Content in Fresh Concrete', 'one test', '1500', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('68159587', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. Standard compaction test. Revised compaction test.', 'One test', '4000', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('10752378', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. Asphalt concrete mix design.', 'one test', '25000', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('24941004', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. Bamboo steel bar bending test', 'root', '300', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('9196777', 'Quality management. Test specifications and standards. Civil engineering and construction inspections. Bamboo steel bar tensile testing', 'root', '500', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('79864260', 'Earthwork. Earthwork transportation costs', 'L.㎥', '137', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('9121552', 'Underground distribution pipelines. Ready-mixed concrete. 210 kgf/cm2', '㎥', '2611', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('90625494', 'Indoor wiring and power distribution line installation technician. Plumbing and electricity', 'Day', '2500', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('31568532', 'Flat top white clay.', 'm²', '40', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('54193837', 'Technician. Night. Measurement', 'Day', '2750', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('16090908', 'Construction measurement. Measurement and layout', 'm²', '30', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('76460539', 'Excavation of structures. Mechanical excavation', '㎥', '80', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('33046464', 'Machine tool operator. Grab machine', 'Hour', '375', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('77701200', 'Machine tool operator. Drilling machine', 'Day', '2000', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('79795010', 'Mechanical demolition. Structural demolition (demolition of structures other than buildings). Reinforced concrete. Shipping included.', '㎥', '1100', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('5334035', 'Paint. One base, two coats', 'm²', '195', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('83131979', 'Plasterer-plastering technician. Plastering', 'Day', '2900', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('11003626', 'Concrete Technician', 'Hour', '410', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('56267415', 'Architectural concrete. Type B', 'm²', '600', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('88231132', 'Asphalt concrete paving. Thickness 5cm', 'm²', '494', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('78339168', 'Asphalt concrete surface layer removed. Thickness 10cm', 'm²', '126', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('75863473', 'Asphalt concrete surface layer removed. Thickness 5cm', 'm²', '82', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('70166708', 'Product. 600V polyvinyl chloride insulated wire (PVC). Stranded wire. 5.5mm2', 'm', '10', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('42462441', 'Product: Stainless steel pipe. Diameter = 5cm. Thickness 2.0mm', 'm', '300', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('34999379', 'Product. Traffic Cone. Height 70cm', 'Piece', '250', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('27415205', 'Product. Portland Cement. Type 2 Cement. Bags. Delivered to site.', 'Bag', '180', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('89889098', 'Products. Geotextiles. Fabrics', 'm²', '50', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('96125636', 'Products. Sealant', 'L', '250', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('42169044', 'Products. Sealing materials. Sealing agents. Silicone fillings', 'm', '50', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('32035886', 'Products. Ceiling. Suspension Rods', 'm²', '80', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('35650176', 'Products. Ceiling. Plastic (PVC)', 'm²', '180', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('53121477', 'Product. Flat plastic warning tape. Polyvinyl chloride (PVC). Width = 150mm', 'm', '10', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('17566185', 'Product. Flat plastic warning tape. Polyvinyl chloride (PVC). Width = 200mm', 'm', '20', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('90152735', 'Product: Folding Plastic Warning Tape', 'm', '10', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('86637649', 'Product. Stone Dump. Stone Block. 30cm ≤ Long Diameter', '㎥', '1600', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('40264926', 'product. Water intake', 'Piece', '4825', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('61367643', 'Product. Grounding conductor. PVC insulated wire (green). Nominal cross-sectional area 14mm2', 'm', '55', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('42436584', 'Product. Grounding conductor. Bare flexible copper stranded wire. Nominal cross-sectional area 100mm2', 'm', '281', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('9736572', 'Product. Ground Rod. Copper-clad steel rod. D19mm x L3.0m', 'Piece', '520', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('1250299', 'Product. Controlled low-strength backfill material. Aggregate for concrete. 90 kg/cm2', '㎥', '1300', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('61510041', 'Products. Construction Fence. Concrete Foundation', 'm', '60', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('83370583', 'Products. Flexible Paving. Fine Aggregate', 'L.㎥', '500', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('75563727', 'Products. Flexible surfacing. Peel-off agent', 'kg', '100', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('13419256', 'Products. Planting. Foreign soil', '㎥', '400', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('9832887', 'Products. Grass Planting. Carpet Grass (Tropical Carpet Grass)', 'm²', '100', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('72160068', 'Products. Road Marking. Paint', 'L', '80', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('28609087', 'Products. Road marking. Road paint', 'L', '210', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('67898694', 'Product. Waterstop. PVC. Type E. (150x9mm, 2 balls)', 'm', '167', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('35594597', 'Product. Waterstop. PVC. Type E. 150x9mm', 'm', '156', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('17778019', 'Products: Water-based cement paint', 'L', '200', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('46843172', 'Product: Asphalt concrete surfacing (Type 1, densely graded). Delivery to site.', 'Metric Ton', '2350', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('9233013', 'Product: Asphalt concrete paving. Coarse aggregate 9.5mm. Viscosity AC(1)-20', '㎥', '5380', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('32787299', 'Products. Asphalt adhesive. Fast-setting oil-soluble asphalt', 'kg', '20', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('49597086', 'Product. Lighting Control Switch. Three-way. 15A', 'Piece', '130', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('38250360', 'Product. Glass. Tempered glass. Flat. t=5mm', '900㎠', '120', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('21172421', 'Product. Glass. Tempered glass. Flat. t=6mm', '900㎠', '100', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('58812137', 'Products. Ecological slope protection. Earth bags', 'Piece', '45', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('72909480', 'Products: White Cement', 'Bag', '350', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('94427530', 'Products. Stone powder', 'kg', '60', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('40603163', 'Products. New Jersey Guardrail', 'Piece', '800', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('82097999', 'Products. Structural steel. Hot-rolled steel. H-beam', 'kg', '20', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('87775215', 'Product. Edge Stone. Pre-cast. 15 ≤ Base Width < 20cm. 15 ≤ Total Height < 20cm', 'm', '560', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('70993218', 'Product: PVC drainage pipe. D = 100mm. Includes pipe fittings', 'm', '150', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('1049999', 'Products. Occupational Safety and Health. General Equipment. Helmet Safety Light (for Mining)', 'Piece', '150', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('89639081', 'Products. Occupational Safety and Health. General Equipment. Hazardous Gas Detectors', 'Set', '2500', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('74437458', 'Products. Occupational Safety and Health. General Equipment. Oxygen Concentrators and Oxygen Concentration Alarms', 'Set', '2000', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('40181935', 'Products. Occupational Safety and Health. Protective Equipment. Respiratory. Gas Masks', 'Piece', '1900', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('89038526', 'Products. Occupational safety and health. Protective equipment. Water rescue equipment. Life jackets', 'Piece', '650', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('13903144', 'Products. Occupational safety and health. Protective equipment. Water rescue equipment. Ropes', 'm', '80', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('18024248', 'Products. Occupational Safety and Health. Protective Equipment. Working at Heights. Safety Belts. Backpack Safety Belts', 'Piece', '1800', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('35496015', 'Products. Toilet paper holder', 'Piece', '1300', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('15492573', 'Product. Dimming control system. Network cable. Cat.6', 'm', '16', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('14366125', 'Product. Slope stabilization horizontal drainage pipe. Drain pipe. PVC pipe (no holes). Pipe diameter = 100mm', 'm', '171', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('99645480', 'Product. Metal. Steel. Steel plate. Thickness 3mm', 'kg', '24', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('74252420', 'Product. Metal. Steel. Steel plate. Thickness 6mm', 'kg', '21', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('20863865', 'Product. Metal. Iron wire. Galvanized. (#8, D=4.191mm)', 'kg', '33', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('36553958', 'Product: Wall tiles. (Porcelain tiles, first-class quality). 300x600mm', 'm²', '867', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('37816686', 'Products. Rebar. Rebar Connector. D19mm', 'Piece', '110', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('81178885', 'Product: Reinforced concrete pipe (Type B). D=2000mm. Tertiary pipe', 'Piece', '42763', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('28270233', 'Product: Reinforced concrete pipe (Type B). D = 400mm. Grade 3 pipe. Excavation and backfill not included.', 'm', '2945', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('96316277', 'Product: Reinforced concrete pipe (Type B). D=900mm. Tertiary pipe', 'Piece', '4500', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('46020613', 'Product: Reinforced concrete pipe culvert. D=300mm', 'm', '1210', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('27326368', 'Product: Reinforced concrete pipe culvert. D=600mm', 'm', '2338', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('92274302', 'Products. Door Hardware. Door Stops/Door Stops/Inlay Trims. Magnetic Door Stops', 'Piece', '500', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('85125977', 'Product. Anti-vibration joint. Nominal pipe diameter 80mm. Stainless steel', 'Piece', '3802', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('35431319', 'Product. Ready-mix concrete material cost. 175kgf/cm2. Type 1 cement', '㎥', '2500', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('67834855', 'Product. Ready-mixed concrete material cost. 280kgf/cm2. Type 2 cement', '㎥', '2750', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('65569635', 'Product. Ready-mixed concrete material cost. 420kgf/cm2', '㎥', '4000', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('33704923', 'Product. Ready-mixed concrete material cost. 80kgf/cm2. Type 1 cement', '㎥', '2046', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('6818112', 'Product. Ready-mix concrete material cost. 80kgf/cm². Type 1 cement. Delivery to construction site.', '㎥', '1900', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('12388090', 'Products. Air Duct. Spiral', 'm', '223', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('85132217', 'Product: High-pressure concrete floor tiles. 80mm thick.', 'm²', '700', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('56851377', 'Product: High-density polyethylene pipe. Straight pipe. Material: PE3408. Maximum operating pressure: 0.98 MPa (10 kgf/cm²). Nominal diameter: 200 mm.', 'm', '650', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('37135391', 'Product: High-density polyethylene pipe. Straight pipe. Material: PE3408. Maximum operating pressure: 0.98 MPa (10 kgf/cm²). Nominal diameter: 300 mm.', 'm', '1350', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('5917225', 'Product: High-density polyethylene pipe. Straight pipe. Material: PE3408. Maximum operating pressure: 0.98 MPa (10 kgf/cm²). Nominal diameter: 400 mm.', 'm', '2200', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('475894', 'Products. Adhesive', 'L', '50', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('44769200', 'Structural concrete. 175kgf/cm2', '㎥', '1800', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('17558317', 'Structural concrete. 210kgf/cm2', '㎥', '2868', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('85511909', 'Structural concrete. 245kgf/cm2', '㎥', '3000', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('35159040', 'Structural concrete. Machine mixed. 175kgf/cm2', '㎥', '1700', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('21687165', 'Decorative carpentry, furniture carpentry, door and window carpentry technicians', 'Day', '3000', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('99486328', 'Road construction and restoration. Sidewalk surface', 'm²', '750', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('59302158', 'Laying technician. Stone', 'Day', '3500', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('74045292', 'Steel structure technician', 'Day', '2100', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('94713081', 'Steel erection technician. daytime', 'Day', '3000', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('57403166', 'rebar. SD420W. Continuous processing and material handling', 'Metric Ton', '29424', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('75283645', 'rebar. Embedded rebar. D19mm', 'One test', '300', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('1297845', 'rebar.', 'kg', '28', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('15015458', 'Prestressing technician. Prestressing steel tendons', 'Hour', '350', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('10099059', 'Precast concrete. Special-shaped blocks. 5 tons. Transport', 'Piece', '430', '0', '1');
INSERT INTO materials (material_id, Item, Unit, PriceAvg, PriceStdev, NoSamples) VALUES ('92747083', 'The remaining land shall be handled by the owner (including soil and water conservation)', 'B.㎥', '408', '0', '1');