CREATE TABLE IF NOT EXISTS pos (
  id INT PRIMARY KEY AUTO_INCREMENT,
  quote_id INT NOT NULL,
  status VARCHAR(50) DEFAULT 'ordered',
  notes TEXT,
  cancelled_at DATETIME NULL,
  created_by INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (quote_id) REFERENCES quotes(id) ON DELETE RESTRICT,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
  INDEX idx_status (status)
);

